### ISSUE TITLE
Can't export to LaTeX (or Beamer or HTML)

### ISSUE THREAD

**Issue by santiagomejia** [joonro/Org-Coursepack#4] opened 2019-12-09 14:10 UTC
The Org-Coursepack looks really promising.  Thanks so much for putting it together.

However, as I was going through the quick start guide I've stumbled upon a problem that I have not been able to solve: none of the export links in "Semester Template.org"  work in my system. Emacs complains:

`eval: Symbol’s function definition is void: let%20`  (for reveal.js)
`eval: Symbol’s function definition is void: org-beamer-export-to-pdf%20nil%20t` (for Beamer)
`eval: Symbol’s function definition is void: org-latex-export-to-pdf%20nil%20t` (for LaTeX).

I've spent a couple of hours yesterday and today trying to figure out what the problem is.  I've tried Googling it, reading the org-mode documentation, and going through your documentation.  But I have not been able to sort this out. If it helps to know, I am using Emacs 26.2 and org-mode 9.3, and while I am not an Emacs or Org-mode poweruser, I have been using them for quite some time now.

**Comment by joonro** [comment] 2019-12-09 18:17
Hi,

Thank you very much for the kind words. I'm sorry you are having trouble with exporting. 

It looks like for some reason your Emacs does not convert `%20` to a space character in reading the org file. For example, I do see `[[elisp:(org-latex-export-to-pdf%20nil%20t)][LaTeX]]` when I open the `Semester Template.org` outside of emacs, but it gets converted to `[[elisp:(org-latex-export-to-pdf nil t)][LaTeX]]` when I open the file in Emacs. 

Could you please let me know which operating system are you using? I created Org-Coursepack in Emacs on Windows, and I wonder if that messes things up.

**Comment by santiagomejia** [comment] 2019-12-09 19:21
Thanks so much for the prompt response.  This solved the problem. I use Ubuntu 16.04 (Xubuntu, to be precise).  When I changed the %20 for simple spaces I was able to export the file.  

(I wish I knew more to be able to propose a solution that is robust across operating systems).

**Comment by joonro** [comment] 2019-12-09 19:23
Thanks! There must be an issue with how Emacs saves file in Windows I think. I will look into it and let you know, ans manually replacing `%20` with ` ` is obviously not ideal. :)

**Comment by santiagomejia** [comment] 2019-12-09 19:25
For the time being I will change it manually.  I wanted to add one thing
that may not be relevant to add in the Github page:

Once the export worked, it took me a bit to realize that for the "Semester
Template.org" to export adequately, it needed to be embedded within all the
files that come with Org-Course. In my initial attempt I had copied the
"Template" folder only onto a completely separate folder.

In the quickstart guide it is stated: "Make a copy of the Template
directory (inside the /Courses directory)."  This could be interpreted as
"make a copy of the file inside the /Courses directory and put it anywhere
you want".

It may be worthwhile to clarify: "Make a copy of the Template directory
inside the /Courses directory (making sure to keep the copy in the same
directory where the Template directory is housed)."

SM
--
Santiago Mejia
Assistant Professor
Fordham University

**Comment by joonro** [comment] 2019-12-09 19:26
Oh by the way, if you don't mind, after you save the file with `%20` replaced with the space character in your system, could you please let me know what it looks like if you open the file in an external text editor? I'm wondering if Emacs does not replace the space character with `%20` in GNU/Linux.

**Comment by santiagomejia** [comment] 2019-12-09 19:27
I'm happy to do so... but I am not sure I understand what exactly it is
that you'd like me to do.

SM.
--
Santiago Mejia
Assistant Professor
Fordham University

**Comment by joonro** [comment] 2019-12-09 19:32
Sorry, what I was talking about was:

1. Manually replace `%20` with the space char in your Emacs
2. Save the file (`Semester Template.org`)
3. Open the file with an external text editor, and see if the spaces in elisp links are replaced by `%20`.

I'm asking this because in my system, if I open the file with Vim for example (see the screenshot below), I do see `%20`'s. However, when I open it with Emacs, `%20` are replaced by the space char.

![image](https://user-images.githubusercontent.com/1063143/70466135-518f5600-1a77-11ea-8d72-2409d8f0d8e2.png)

Also, thank you very much for the suggestion - I will incorporate it in the documentation.

**Comment by joonro** [comment] 2019-12-09 22:09
Hi, 

Something is strange - I just installed Ubuntu in my machine using WSL, and installed Emacs. When I opened `Semester Template.org`, the links were correctly specified (i.e., `%20` were correctly replaced by space character). 

I wonder if one of the settings is causing the issue -- it is hard for me to troubleshoot because I cannot reproduce the problem. Will report back if I find something.

**Comment by santiagomejia** [comment] 2019-12-10 01:01
Dear Joon

I've replaced the %20 with spaces, saved the file, and attached it in case
you want to check it out.

I am not sure what happens when you open it with VIM; it is against my
religion to use it ;).  But when I opened it with my basic notepad and with
Libreoffice, the spaces show up as spaces.  I think that it may be only
windows which changes spaces in the links to %20.

By the way, I suspect that there may also be a similar problem with another
character: "%5B" (in the link to open the PDF file just the link to open
the LaTeX file).
[[elisp:(org-open-link-from-string (concat "%5B%5Bfile:./" (org-entry-get
nil "EXPORT_FILE_NAME") ".pdf%5D%5D"))][PDF]]

In my system this link does not work either.  When I click on it it
complains: "user-error: No valid link in "%5B%5Bfile:././Syllabus/Syllabus
(Section 2).pdf%5D%5D""

SM.
--
Santiago Mejia
Assistant Professor
Fordham University

**Comment by santiagomejia** [comment] 2019-12-10 02:43
BTW... Would you like me to continue to point out other typos of issues as
I go through the documentation?

For instance, things like this?

In
https://joonro.github.io/Org-Coursepack/Lectures/01%20Course%20Introduction.html
there is a typo:

"Code can be inputting [Should be *inputted*] using code blocks
<https://orgmode.org/manual/Structure-of-code-blocks.html>, which can be
easily inserted by pressing <s and then <TAB> key in Org mode.

SM.
--
Santiago Mejia
Assistant Professor
Fordham University

**Comment by joonro** [comment] 2019-12-10 04:30
Yes of course! Do you mind creating PRs for those? Making changes on the documentation is very easy, you can directly edit the file on Github, and create a PR from there directly. Of course if it is too much then you can just let me know --- thank you very much again.

Regarding the special character issue, please let me keep looking into it --- it is strange since in my Ubuntu installation, Emacs could open the file without any problem. Let me ask around and see what is going on.

**Comment by santiagomejia** [comment] 2019-12-10 15:27
I am happy to do so.  But, unfortunately, I am not quite sure how to (I am
not a computer scientist, I am a philosophy professor).

Allow me to ask you two (hopefully short) questions: If I want to edit the
documentation for the first lecture, where is this document located in the
tree of files in Github?  And how do I edit it?  (no need to explain the
second question in-depth, just a couple of pointers of what to look up in
Google would be enough).

SM.
--
Santiago Mejia
Assistant Professor
Fordham University

**Comment by santiagomejia** [comment] 2019-12-10 19:03
Never mind.  I'm done reading the documentation and there is only one more
typo I found.  It is probably easier for both of us if I simply tell you
about it.

In
https://joonro.github.io/Org-Coursepack/Lectures/06%20Semester%20Org%20Files%201%204%20Introduction.html
You talk about the
SEMESTER_INFO: Drawer
The :SEMESTER_INFO: drawer has macros containing information about the
course that is common across sections but specific to the semester.

However, in the template that I downloaded, this drawer is actually called:
"COURSE_INFO".  I'm not sure if this is a typo in the documentation or in
the template.  Either way, you should change one of them.

SM
--
Santiago Mejia
Assistant Professor
Fordham University

**Comment by joonro** [comment] 2020-03-02 05:51
Hi -

I'm very sorry for the late response. After I updated my Emacs and orgmode I started experiencing the same broken link issue - the issue is now fixed. Thanks for the typo as well!

**Closed as completed by joonro** 2020-03-02 05:51 UTC
